### ISSUE TITLE
Selected item does not always match marked active item

### ISSUE THREAD

**Issue by Dogbombs** [lukaszfiszer/selectnav.js#1]
Using selectnav.js downloaded on 18th June 2012 at 1030, testing integration with jQuery Mobile 1.1.0 for use in a mobile website/phoneGap application.  Testing via Chrome beta browser on Android ICS.

HTML: 

``` html
<ul id="nav">
   <li><a href="03_intro.html#intro" class="act">Introduction</a></li>
   <li><a href="03_intro.html#tells">About the game</a></li>
   <li><a href="03_intro.html#structure">From Structure to Story</a></li>
   <li><a href="03_intro.html#chapters">Chapters in this app</a></li>
   <li><a href="03_intro.html#modes">Styles of Play</a></li>
</ul>
```

JS:

``` javascript
selectnav('nav', {
   activeclass: 'act',
   label: false
});
```

HTML document is a jQuery Mobile multi-page document (so there are 5 nav bars, nav, nav1, nav2, etc., 1 in the header of each page div).  When using the navigation dropdown in the header (which looks superb, by the way), sometimes the selected item will not be the page displayed - e.g. the page haeding might be "Chapters" but the navigation displays "Styles of Play".  Navigation always takes you to the page you selected.

class="act" is set correctly on each page.  This is an intermittent error that, while not preventing use, may introduce confusion to users.

**Comment by lukaszfiszer** [comment]
Have you tried to disable the autoselection? It is possible that in some circumstances it interfere with the explicitly set active class.

``` javascript
selectnav('nav', {
   activeclass: 'act',
   label: false,
   autoselect: false
});
```

**Comment by Dogbombs** [comment]
Fixed it.  Thank you very much.
