### ISSUE TITLE
Menu For Wordpress 

### ISSUE THREAD

**Issue by imalisiddique** [lukaszfiszer/selectnav.js#13]
Hello 

I want to create menu for WordPress ,Please provide be code how to do this.
when i add selectnav.js then three menu will show .

**Comment by ruudbwai** [comment]
check your css. selectnav should only show on small screen, and big menus hidden. good luck!

**Comment by RibacDj** [comment]
Can someone tell me where I change number and names of menu items? I have some WP theme and they are using this .js but the probem is that on smaller screens menu is becoming drop menu (that is ok) but it's adding new item "Menu" on top, and that button do nothing. When I inspect I can se generated code 
 /_<select class="selectnav" id="selectnav1">
      <option value="">Menu</option>
      <option value="http://localhost/null-object/#home-section-2" selected="">HOME</option>
      <option value="http://localhost/null-object/team/">ABOUT</option>
      <option value="http://localhost/null-object/services-2/">SERVICES</option>
       <option value="http://localhost/null-object/blog/">BLOG</option>
</select>_/
Simply I don't need "/*<option value="">Menu</option>"  :) where to change that, thanks!
