### ISSUE TITLE
Doing this working for a Drupal website

### ISSUE THREAD

**Issue by webmasterpf** [lukaszfiszer/selectnav.js#20]
Hi

i'm using your plugin to do a responsive nav on a drupal website.So i created a block with this code into:
`<div class="content">
      <ul class="horizontal-nav">
<li><a href="link">Item </a></li>
<li><a href="link">Item </a></li>
<li><a href="link">Item </a></li>
<li><a href="link">Item </a></li>
<li><a href="link">Item </a></li>
</ul>    </div>`

and using as you say : 
adding js file via the .info drupal theme file : ok
adding script like:
`<script>selectnav('.horizontal-nav'); </script>`

but no select created with the selectnav class.

what is missing ?

thanks

**Comment by webmasterpf** [comment]
fixed it by myself with little modifications :
- added an subnav id to the `<ul>` like :
  `<ul class="horizontal-nav" id="subnav">`
- modifying the script : 
  `<script>selectnav('subnav'); </script>`

then i get the select menu created and displaying it on mobile screen.

great

**Comment by lukaszfiszer** [comment]
Indeed, you can currently pass only an element id to the selectnav contructor. I plan to add support for other selectors (in jQuery style), but currenly I dont have enough of free time to take care of it. If you'd like submit a PR, it would be highly appreciated.
