### ISSUE TITLE
nested menu

### ISSUE THREAD

**Issue by mauriciocgpereira** [lukaszfiszer/selectnav.js#3]
Hi,

I've got a kind-of megamenu.

The html looks more or less:

ul class="...." id="..."
    li
        span
            h2
                item 1 
                br/
            /h2
            span
                item 1 subtitle
            /span
        /span
        div class="..."
            div class="...."
                img ....
            /div
        div class="...."
            div class="...."
                h3 
                    subtitem1
                /h3
                ul
                    li
                        h4
                            a href="#"
                                subsubitem1
                            /a
                        /h4
                    /li
                /ul
            /div
        /div
    /li
/ul

The issue is that selectnav detects delivers a drop down only with the first level elements

item1 item1subtitle, 

what I wanted was:

item1 item1subtitle <br/>
- subitem1 <br/>
  -- subsubitem1

Is it possible?

Thanks in advance

**Comment by lukaszfiszer** [comment]
Sorry for a late answer, I was on holiday. Could you put the structure of your menu on http://jsbin.com/ or http://jsfiddle.net/ and link it here? Posted here in plain text, it's is quite unreadable.

**Comment by mauriciocgpereira** [comment]
Hi there,

Thanks for your email and for your concern. (and sorry for my bad english J )

The link with the menu structure: http://jsbin.com/atejih/1/edit

Thanks,

Maurício Pereira

De: Lukasz [mailto:notifications@github.com] 
Enviada: sexta-feira, 24 de Agosto de 2012 14:47
Para: lukaszfiszer/selectnav.js
Cc: Mauricio Pereira
Assunto: Re: [selectnav.js] nested menu (#3)

Sorry for a late answer, I was on holiday. Could you put the structure of your menu on http://jsbin.com/ or http://jsfiddle.net/ and link it here? Posted here in plain text, it's is quite unreadable.

—
Reply to this email directly or view it on GitHub https://github.com/lukaszfiszer/selectnav.js/issues/3#issuecomment-8001706 . 

  https://github.com/notifications/beacon/tH-FKv3F6g-OLE5VUPE6KONDgHSDRBU0_3OOWYV5VLl9AeuuwjrXxOYrI3n-4xBp.gif

**Comment by lukaszfiszer** [comment]
Hi!

Selectnav.js was designed to be used with simple `<ul>`style navigation, and not with more complex structures like yours. Of course, it can handle multi-level nested list but they need to be structured in a certain way, as shown in provided examples. So you can either adjust your menu's structure, or find some other script that will be more flexible. 

Moreover, your menu looks more like a table of content to me. Are you sure you want to transform it into a dropdown menu for mobile users? That seems like not a good solution taking into account the length and the complexity of your menu. Keep in mind how `<select>` looks like on mobile devices: http://media.smashingmagazine.com/wp-content/uploads/2011/12/prog-resp-nav_13.jpg  I would rather leave it like it is now and adapt it to small screens by using media queries.

**Comment by mauriciocgpereira** [comment]
Initially I tried using mediaqueries, but I think the select is more appropriate to mobile devices.

With mediaqueries, adjusting the menu remained big.

Thanks anyway,

Maurício Pereira

De: Lukasz [mailto:notifications@github.com] 
Enviada: sexta-feira, 24 de Agosto de 2012 16:13
Para: lukaszfiszer/selectnav.js
Cc: Mauricio Pereira
Assunto: Re: [selectnav.js] nested menu (#3)

Hi!

Selectnav.js was designed to be used with simple <ul>style navigation, and not with more complex structures like yours. Of course, it can handle multi-level nested list but they need to be structured in a certain way, as shown in provided examples. So you can either adjust your menu's structure, or find some other script that will be more flexible. 

Moreover, your menu looks more like a table of content to me. Are you sure you want to transform it into a dropdown menu for mobile users? That seems like not a good solution taking into account the length and the complexity of your menu. Keep in mind how <select> looks like on mobile devices: http://media.smashingmagazine.com/wp-content/uploads/2011/12/prog-resp-nav_13.jpg I would rather leave it like it is now and adapt it to small screens by using media queries.

—
Reply to this email directly or view it on GitHub https://github.com/lukaszfiszer/selectnav.js/issues/3#issuecomment-8004203 . 

  https://github.com/notifications/beacon/tH-FKv3F6g-OLE5VUPE6KONDgHSDRBU0_3OOWYV5VLl9AeuuwjrXxOYrI3n-4xBp.gif

**Comment by lukaszfiszer** [comment]
I still think that selectnav.js should not be used for such long list of links. One alternative is to use media queries to hide deeply nested parts of your menu - something similar is done on mobile version of wikipedia to show/hide parts of articles. See http://en.m.wikipedia.org/wiki/Systems_theory. There are of course plenty other solutions, but it's not really a place to discuss them.

**Comment by mauriciocgpereira** [comment]
Ok,

Thanks anyway

De: Lukasz [mailto:notifications@github.com] 
Enviada: sexta-feira, 24 de Agosto de 2012 17:38
Para: lukaszfiszer/selectnav.js
Cc: Mauricio Pereira
Assunto: Re: [selectnav.js] nested menu (#3)

I still think that selectnav.js should not be used for such long list of links. One alternative is to use media queries to hide deeply nested parts of your menu - something similar is done on mobile version of wikipedia to show/hide parts of articles. See http://en.m.wikipedia.org/wiki/Systems_theory. There are of course plenty other solutions, but it's not really a place to discuss them. 

—
Reply to this email directly or view it on GitHub https://github.com/lukaszfiszer/selectnav.js/issues/3#issuecomment-8007781 . 

  https://github.com/notifications/beacon/tH-FKv3F6g-OLE5VUPE6KONDgHSDRBU0_3OOWYV5VLl9AeuuwjrXxOYrI3n-4xBp.gif
