### ISSUE TITLE
The Code "link.parentElement." in line 110 , it is not compatible on FF

### ISSUE THREAD

**Issue by apei830** [lukaszfiszer/selectnav.js#6]
The Code "link.parentElement." in line 110 , it is not compatible on FF

It can be replace with "link.parentNode"

**Comment by apei830** [comment]
the same as insertAdjacentHTML, in FF, it is not a function of an element

**Comment by lukaszfiszer** [comment]
Sorry for late response, I had no time to take care over the project for last few months but now I plan to resume working on it.

Concerning the bug - I don't get any error in FF. What version are you using? Could you copy the error from the console?

Thanks

**Comment by stevengliebe** [comment]
It affects Firefox 8 and earlier. parentNode was introduced to Firefox in version 9 according to this: http://stackoverflow.com/questions/8685739/difference-between-dom-parentnode-and-parentelement

Sure enough, when parentElement is replaced with parentNode, everything seems to works fine in Firefox 8.

**Comment by stevengliebe** [comment]
Here's the error:

``` javascript
link.parentElement is undefined
```

Line 110

**Comment by lukaszfiszer** [comment]
Hey @stevengliebe , thank you for pointing this out! Would you mind submitting a pull request with the fix?

**Comment by stevengliebe** [comment]
Will do.

**Comment by lukaszfiszer** [comment]
Merged! Thanks a lot!
