### ISSUE TITLE
how to use selectnav.js in joomla

### ISSUE THREAD

**Issue by creotip** [lukaszfiszer/selectnav.js#7]
hi! great job you did here...i would like to know how to use it in joomla based menu. im not a specialist in coding. thank you!

**Comment by lukaszfiszer** [comment]
he creotip, sorry for late response. Unfortunately I never used joomla in my life, but as with any CMS I imagine you should do some editing of html templates. Anyway, your question is rather joomla-specific and should ask it on some joomla forum/mailing group.
